export type ClientProduct = {
  title: string;
  brand: string;
  image: string;
  imageAlt: string;
  tall?: boolean; // use taller image container
  galenique: string; // e.g., "Gélules", "Poudre", "Comprimés", "Gummies", "Barre", "Vinaigrette", "Gommage"
  bienfaits: string; // e.g., "Articulations", "Beauté de la peau", "Peau & Articulations"
  formulation: string;
  href: string;
};

export const clientProducts: ClientProduct[] = [
  {
    title: "Collagène végétarien articulaire",
    brand: "Valebio",
    image: "/images/collagène-articulaire.svg",
    imageAlt: "Coquille de j'oeufnesse",
    tall: true,
    galenique: "Gélules",
    bienfaits: "Articulations",
    formulation: "Reggenerate + acide hyaluronique + curcuma vitamine C",
    href: "https://www.valebio.com/nos-produits/745-collagene-vegetarien-articulaire-en-gelules.html?srsltid=AfmBOoo4QdA-VfsYKCBx7nl3fKBUtzucFfA_REUkhsU-HKUT6EtnqHcK",
  },
  {
    title: "Collagène végétarien beauté",
    brand: "Valebio",
    image: "/images/collagene-beaute-valebio.svg",
    imageAlt: "Coquille de j'oeufnesse",
    tall: true,
    galenique: "Gélules",
    bienfaits: "Beauté de la peau",
    formulation: "Reggenerate + acide hyaluronique + vitamine C",
    href: "https://www.valebio.com/nos-produits/743-collagene-vegetarien-beaute-en-gelules.html",
  },
  {
    title: "Collagène végétarien",
    brand: "Oemine",
    image: "/images/collagène-veggie.svg",
    imageAlt: "Collagène végétarien",
    tall: true,
    galenique: "Gélules",
    bienfaits: "Anti-âge & Articulation",
    formulation: "Reggenerate + Cynorrhodon",
    href: "https://oemine.fr/produit/collagene-vegetarien/",
  },
  {
    title: "Cure peau repulpée",
    brand: "Epycure Laboratoire",
    image: "/images/cure-peau-repulpee.svg",
    imageAlt: "Cure peau repulpée",
    tall: true,
    galenique: "Gélules",
    bienfaits: "Beauté de la peau",
    formulation: "Reggenerate + Bourrache + Vitamine C + Sélénium + Vitamine E + Zinc + Biotine + Vitamine B6",
    href: "https://epycure.com/products/cure-peau-repulpee",
  },
  {
    title: "Hair Skin Nails",
    brand: "Nutrielement",
    image: "/images/hair-skin-nails.svg",
    imageAlt: "Hair Skin Nails",
    galenique: "Gélules",
    bienfaits: "Beauté globale peau, cheveu & ongles",
    formulation: "Reggenerate + Kératine + Sélénium + Zinc + Vitamine C + Biotine + MSM",
    href: "https://www.nutrielement.com/products/hair-skin-nails-gelules",
  },
  {
    title: "Collagène végétarien",
    brand: "SIHO",
    image: "/images/collagène-veggie-2.svg",
    imageAlt: "Collagène végétarien",
    galenique: "Poudre",
    bienfaits: "Peau & Articulations",
    formulation: "Reggenerate™",
    href: "https://thesihoeffect.com/fr-ch/products/collagene-vegetarien-novolife?_pos=1&_psq=vegeta&_ss=e&_v=1.0",
  },
  {
    title: "Kotor Collagène",
    brand: "Kotor Pharma",
    image: "/images/kotor-collagène.svg",
    imageAlt: "Bosw’Egg",
    galenique: "Gélules",
    bienfaits: "Peau & Articulations",
    formulation: "Reggenerate + siliium végétal + Vitamine C + glucosamine + chondroïtine + kératine",
    href: "https://kotorpharma.com/produit/kotor-collagene/?srsltid=AfmBOopaL8uwuCUuXgGoyIKytksCoNUQR6sKzA9VFQdeUHm1G1JVYxx5",
  },
  {
    title: "Barre Collagène Matcha Chocolat",
    brand: "Supernature",
    image: "/images/barre-collagène-matcha-choco.svg",
    imageAlt: "Barre Collagène Matcha Chocolat",
    galenique: "Barre",
    bienfaits: "Beauté de la peau",
    formulation: "Reggenerate",
    href: "https://www.supernature.paris/products/barre-collagene-matcha-chocolat?pr_prod_strat=e5_desc&pr_rec_id=68f870c10&pr_rec_pid=10515038437710&pr_ref_pid=10397196353870&pr_seq=uniform&variant=53170145624398",
  },
  {
    title: "Chaï Latte Collagène",
    brand: "Supernature",
    image: "/images/chai-latte-collagène.svg",
    imageAlt: "Chaï Latte Collagène",
    galenique: "Poudre",
    bienfaits: "Beauté de la peau",
    formulation: "Reggenerate",
    href: "https://www.supernature.paris/products/chai-latte-collagene-100g-supernature-x-la-main-noire?variant=52684636619086",
  },
  {
    title: "Dermavits",
    brand: "Lepivits",
    image: "/images/dermavits.svg",
    imageAlt: "Dermavits",
    galenique: "Poudre",
    bienfaits: "Beauté de la peau",
    formulation: "Reggenerate + Vitamine C + Vitamine E",
    href: "https://lepivits.be/fr/nutra-complexes/155-dermavits-5430003465417.html",
  },
  {
    title: "Membrane Coquille d'Oeuf Curcuma",
    brand: "Curcumaxx",
    image: "/images/membrane-coquille-curcuma.svg",
    imageAlt: "Membrane Coquille d'oeuf Curcuma",
    galenique: "Gélules",
    bienfaits: "Articulations",
    formulation: "Reggenerate + Curcuma",
    href: "https://curcumaxx-france.com/boutique/gelules/curcumaxx-coquille-doeuf-curcuma-piluliers-60-gelules/",
  },
  {
    title: "Mouvement",
    brand: "Byogénie",
    image: "/images/mouvement.svg",
    imageAlt: "Mouvement avec Collagène",
    galenique: "Gélules",
    bienfaits: "Articulations",
    formulation: "Reggenerate + Collagène + Acide hyaluronique + Bambou + Curcuma + Saule + cuivre",
    href: "https://www.byogenie-projet.com/mouvement-avec-collagene/",
  },
  {
    title: "C’est la Chic(k) : Eggshell Membrane Collagen Scrub Soap Set",
    brand: "Vicky en france",
    image: "/images/collagène-scrub-soap.svg",
    imageAlt: "Collagen Scrub Soap Set",
    galenique: "Gommage",
    bienfaits: "Beauté de la peau",
    formulation: "Reggenerate + Graines de lin + Romarin + Coquille de noix + Sel marin + Beurre de karité",
    href: "https://vickyenfrance.com/products/cest-la-chick",
  },
  {
    title: "Collagen+ Vinaigrett",
    brand: "Archie",
    image: "/images/collagène-vinaigrette.svg",
    imageAlt: "Collagen Vinaigrett",
    galenique: "Vinaigrette",
    bienfaits: "Beauté de la peau",
    formulation: "Reggenerate +",
    href: "https://myarchie.co/products/vinaigrette-collagene?srsltid=AfmBOop5_D_OIqmEsZKJ_D_cTm_m6bMM3qivokhEKAHScr7JffRqkSX1",
  },
  {
    title: "N°2 Collagene +",
    brand: "Equi Nutri Laboratoire",
    image: "/images/mouvement-collagène+.svg",
    imageAlt: "N°2 Collagene +",
    galenique: "Gélules",
    bienfaits: "Peau & Articulations",
    formulation: "Reggenerate + Prêle + Vitamine C",
    href: "https://www.equi-nutri.be/fr/produit/314/n2-artiflexx/",
  },
  {
    title: "Suivimine Arthro",
    brand: "Therascience",
    image: "/images/suivimine.svg",
    imageAlt: "Mouvement Collagène +",
    galenique: "Comprimés",
    bienfaits: "Articulations",
    formulation: "Reggenerate + Boswellia + Glucosamine + Chondroïtine",
    href: "https://www.therascience.com/fr_fr/suvimine-arthro-phy503.html?srsltid=AfmBOoq5v5rEEecPjlByjaxSAfqcmG1lGUoJhFtIGQNyqRpJOmqJ3axv",
  },
  {
    title: "Laboratoire Motima",
    brand: "Silinovea",
    image: "/images/silinovea.svg",
    imageAlt: "Silinovea du Laboratoire Motima",
    galenique: "Gélules",
    bienfaits: "Articulations & Peau",
    formulation: "Vitamine C + Bambou Tabashir + L-Tyrosine + Lithothamne (iode) + Reggenerate + Zinc + Vitamine B5 + Vitamine B6 + Vitamine B8",
    href: "https://motima.fr/products/silinovea",
  },
  {
    title: "Mium Lab",
    brand: "Gummies Collagène VG",
    image: "/images/gummies-collagene.svg",
    imageAlt: "Gummies Collagène VG",
    galenique: "Gummies",
    bienfaits: "Beauté de la peau",
    formulation: "Collagène végétarien Reggenerate pour raffermir la peau",
    href: "https://www.miumlab.com/products/gummies-collagene-vg?srsltid=AfmBOorjA-TyxTjphKz5lt-CXOYTTpX3Zys5tPHKJLhaSUH2YMR2csp2",
  },
  {
    title: "Roches Marines Laboratoire",
    brand: "Calcium marin + Collagène",
    image: "/images/calcium-collagene.svg",
    imageAlt: "Calcium marin + Collagène",
    galenique: "Gélules",
    bienfaits: "Articulations",
    formulation: "Complément alimentaire à base de calcium marin (lithothamne) et de collagène issu de membrane d’œuf française",
    href: "https://roches-marines.fr/tous-nos-produits/105-95-calcium-marin-collagene.html",
  },
  {
    title: "Ilko nutrition",
    brand: "Arthro Health",
    image: "/images/arthro-health.svg",
    imageAlt: "Arthro Health",
    galenique: "Gélules",
    bienfaits: "Articulations",
    formulation: "Apporte aux muscles et articulations les nutriments nécessaires à leurs reconstructions",
    href: "https://www.ilkonutrition.fr/products/arthro-health",
  },
  {
    title: "Lehning Laboratoire",
    brand: "Rexoflex beauté",
    image: "/images/collagene-veggie-renoflex.svg",
    imageAlt: "Rexoflex beauté",
    galenique: "Gélules",
    bienfaits: "Beauté de la peau",
    formulation: "Conçu pour améliorer la fermeté et l’élasticité de votre peau ainsi que la beauté de vos cheveux et ongles, il convient idéalement à un régime végétarien",
    href: "https://www.lehning.com/produit/rexoflex-beaute",
  },
];

