export type RTMForm = 'gelules' | 'comprime' | 'poudre' | 'gummies' | 'barres';
export type RTMBenefit = 'beauty' | 'joints';

export type ReadyToMarketProduct = {
  id: string;
  title: string;
  subtitle: string; // tagline under title
  image: string;
  imageAlt: string;
  form: RTMForm;
  benefit: RTMBenefit;
  galenique: string;
  bienfaits: string;
  aroma: string;
  formulation: string;
  moq: string;
};

export const readyToMarketProducts: ReadyToMarketProduct[] = [
  {
    id: 'joeufnesse',
    title: 'Coquille de j’œufnesse',
    subtitle: "Ta peau mérite un petit coup de n’œuf !",
    image: '/images/joeufnesse.svg',
    imageAlt: "Coquille de j'oeufnesse",
    form: 'gelules',
    benefit: 'beauty',
    galenique: '60 gélules',
    bienfaits: 'Elasticité – Fermeté – Éclat',
    aroma: '—',
    formulation: 'Reggenerate™, Probiotiques, Acérola, Zinc',
    moq: 'dès 500 pots',
  },
  {
    id: 'eggstra-jeunesse',
    title: 'Eggstra Jeunesse',
    subtitle: 'Ta peau a bien besoin d’un petit coup de poule !',
    image: '/images/eggstrajeunesse.svg',
    imageAlt: 'Eggstra Jeunesse',
    form: 'comprime',
    benefit: 'beauty',
    galenique: '60 comprimés',
    bienfaits: 'Elasticité – Fermeté – Éclat',
    aroma: 'Tropical',
    formulation: 'Reggenerate™, Coenzyme Q10, acérola',
    moq: 'dès 2500 pots',
  },
  {
    id: 'vie-en-rose',
    title: 'La Vie en Rose Oeuf',
    subtitle: 'La beauté en poudre par eggcellence !',
    image: '/images/vieenrose.svg',
    imageAlt: 'La Vie en Rose Oeuf',
    form: 'poudre',
    benefit: 'beauty',
    galenique: 'Pot 105g / Stick 3,5g',
    bienfaits: 'Elasticité – Fermeté – Éclat',
    aroma: 'Cerise',
    formulation: 'Reggenerate™, Pétales de rose, Grenade, Acérola',
    moq: 'dès 1666 pots',
  },
  {
    id: 'poule-oeufs-or',
    title: 'La Poule Aux Oeufs d’or',
    subtitle: 'Un trésor pour les articulations pondu par la nature !',
    image: '/images/pouleauxoeufsdor.svg',
    imageAlt: "La Poule Aux Oeufs d’or",
    form: 'gelules',
    benefit: 'joints',
    galenique: '60 gélules',
    bienfaits: 'Souplesse - Mobilité - Confort',
    aroma: '—',
    formulation: 'Reggenerate™, Curcuma, Vitamine D',
    moq: 'dès 500 pots',
  },
  {
    id: 'boswegg',
    title: 'Bosw’Egg',
    subtitle: "Douleurs articulaires ? Croque, c'est réglé.",
    image: '/images/boswegg.svg',
    imageAlt: 'Bosw’Egg',
    form: 'comprime',
    benefit: 'joints',
    galenique: '90 comprimés',
    bienfaits: 'Souplesse - Mobilité - Confort',
    aroma: 'Cerise',
    formulation: 'Reggenerate™, Boswellia, Vitamine C',
    moq: 'dès 1666 pots',
  },
  {
    id: 'egglixir',
    title: "L'Egglixir",
    subtitle: 'La beauté en poudre par eggcellence !',
    image: '/images/egglixir.svg',
    imageAlt: "L'Egglixir",
    form: 'poudre',
    benefit: 'joints',
    galenique: 'Pot 105g / Stick 3,5g',
    bienfaits: 'Souplesse - Mobilité - Confort',
    aroma: 'Mojito',
    formulation: 'Reggenerate™, Bambou, Prêle des champs',
    moq: 'dès 1666 pots',
  },
  {
    id: 'comme-noeuf',
    title: "Comme n'œuf !",
    subtitle: 'Une reggenerescence cutanée ultra-vitaminée !',
    image: '/images/commenoeuf.svg',
    imageAlt: "Comme n'œuf !",
    form: 'gummies',
    benefit: 'joints',
    galenique: '60 gummies',
    bienfaits: 'Elasticité - Fermeté - Eclat',
    aroma: 'Fraise',
    formulation: 'Reggenerate™, Vitamine C',
    moq: 'dès 120 pots',
  },
  {
    id: 'yen-a-pas-doeuf',
    title: "Y’en a pas d’œuf comme lui",
    subtitle: 'Ta peau mérite un peu d’egg-clat !',
    image: '/images/yenapasdoeufcommelui.svg',
    imageAlt: "Y’en a pas d’œuf comme lui",
    form: 'comprime',
    benefit: 'joints',
    galenique: '60 comprimés bicouches',
    bienfaits: 'Elasticité - Fermeté - Eclat',
    aroma: 'Cerise',
    formulation: 'Reggenerate™, Probiotiques, Vitamine C',
    moq: 'dès 5000 pots',
  },
  {
    id: 'eggsplosif',
    title: "L'Eggsplosif",
    subtitle: 'Une eggsplosion de saveur au service de la peau !',
    image: '/images/eggsplosif.svg',
    imageAlt: "L'Eggsplosif",
    form: 'poudre',
    benefit: 'beauty',
    galenique: 'Stick de 2g',
    bienfaits: 'Souplesse - Mobilité - Confort',
    aroma: 'Framboise',
    formulation: 'Reggenerate™, Vitamine C',
    moq: 'dès 4666 boîtes de 30 sticks',
  },
  {
    id: 'barre-noisette',
    title: 'Barre collagéniale noisette',
    subtitle: 'Délici-oeuf-sement saine et eggceptionnelle pour votre peau !',
    image: '/images/barre-noisette.svg',
    imageAlt: 'Barre collagéniale noisette',
    form: 'barres',
    benefit: 'beauty',
    galenique: 'barre de 40g',
    bienfaits: 'Elasticité - Fermeté - Eclat',
    aroma: 'Noisette',
    formulation: 'Reggenerate™, Vitamine C, Vitamine E, Calcium, Phosophore',
    moq: 'dès 4000 barres',
  },
  {
    id: 'barre-choco',
    title: 'Barre collagéniale choco',
    subtitle: 'Délici-oeuf-sement saine et eggceptionnelle pour votre peau !',
    image: '/images/barre-choco.svg',
    imageAlt: 'Barre collagéniale choco',
    form: 'barres',
    benefit: 'beauty',
    galenique: 'barre de 36g',
    bienfaits: 'Elasticité - Fermeté - Eclat',
    aroma: 'Chocolat - graine de courges torréfiées',
    formulation: 'Reggenerate™, Vitamines A, B1, B2, B3, B5, B6, B8, B9,  B12, C, E',
    moq: 'dès 1000 pots',
  },
];

